spring:
  #通用数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.98:3306/mall_user?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true
    username: root
    password: jyIsTpYmq7%Z

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.mykine.mall.user.model

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
